### ISSUE TITLE
NS 2023.2: Global Search Dropdown not working

### ISSUE THREAD

**Issue by burkybang** [burkybang/SuiteAdvanced-Feedback#100]
### Discussed in https://github.com/burkybang/SuiteAdvanced-Feedback/discussions/99

<div type='discussions-op-text'>

<sup>Originally posted by **@Travis048** September 12, 2023</sup>
I've noticed that since the last NetSuite update the dropdown for the global search is not working again. You can click on it and it will show the selections of record types but your selection doesn't actually work. This definitely isn't super important but it is a handy feature if you get a chance. Thanks!</div>

**Comment by burkybang** [comment]
@Travis048 I've resolved this on my end, and the fix will be in the next release. Thanks for reporting it!

**Comment by Travis048** [comment]
Awesome! Thank you!

**Comment by burkybang** [comment]
The new release is out now
