### ISSUE TITLE
Entire NetSuite Header disappearing when disabling SuiteAdvanced for an account

### ISSUE THREAD

**Issue by brisimmons105** [burkybang/SuiteAdvanced-Feedback#101]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 
Entire NetSuite header is hidden when disabling SuiteAvanced for a specific account.
___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 
1. _Choose 'Disabled for this Account' from the SuiteAdvanced menu bar
2. _Watch header disappear

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: 
The header to stay there, and SuiteAdvanced to be disabled for the account.

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
I'm unable to reproduce this. Which version of NetSuite and SuiteAdvanced are you on?

**Comment by brisimmons105** [comment]
Sandbox account, NetSuite (Edition: United States) Release 2023.2
SuiteAdvanced v28.2.0

**Comment by burkybang** [comment]
I still cannot reproduce the issue. Please email me at support@suiteadvanced.com to schedule a meeting, so I can investigate in your browser.

**Comment by burkybang** [comment]
Thanks for meeting with me.

It seems the workaround mentioned in this other issue also applies to this issue.

https://github.com/burkybang/SuiteAdvanced-Feedback/issues/103#issuecomment-1758585783
