### ISSUE TITLE
Un Intended Bug - Due to recent fix regarding picking ticket bulk printing

### ISSUE THREAD

**Issue by alternativetie2** [burkybang/SuiteAdvanced-Feedback#108]
**Describe the bug**
Adam I unfortunately am running into another bug where I am unable to print a picking ticket now when I am on the order itself. See images below. I have also tested of course and removed SA extension on a clean chrome profile and it worked. I am providing my images below.  

Adam - Please also note that when you hit "Print Picking Ticket" it opens the new tab with the file. However everything is blank. You have to do a cnt+r or refresh to get the actual file in view. Obviously not a huge bug. But a bug nevertheless. 

Please let me know if you need more info to replicate this on your own. We are using advanced pdf/html native netsuite forms for these options as well. 

Answer: 

![SA1](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/124277984/e3133c89-df52-46d6-9891-e2cc1a674575)

**Comment by burkybang** [comment]
The new release is out now. It was just approved.
