### ISSUE TITLE
Create New Script shortcut leads to blank page

### ISSUE THREAD

**Issue by Fluzzroz** [burkybang/SuiteAdvanced-Feedback#109]
**Describe the bug**
After uploading a new script file in the SuiteScript/... filecabinet folder, I clicked the + shortcut icon used to create a script record from the file. 
The browser opened a new page, which remained blank. The address was https://9346853.app.netsuite.com/app/common/scripting/uploadScriptFile.nl?scriptfile=1157

Answer: 

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to any .js file in the file cabinet_
2. _Click on the + icon next to the file_
3. _witness blank page_

Answer: 

___

**Expected behavior**
_Previously, this would lead to https://9346853.app.netsuite.com/app/common/scripting/uploadScriptFile.nl with the correct script file selected_

Answer: 

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 

___

**Additional context**
_After going the old way (click customization>scripting>scripts>new) and selecting my script, I was taken to this URL:
https://9346853.app.netsuite.com/app/common/scripting/script.nl?scriptfile=1157&scripttype=CLIENT&apiversion=2.1&package=_

Answer:

**Comment by burkybang** [comment]
Thanks! Will check it out

**Comment by burkybang** [comment]
I have tried and tried, but I can't seem to reproduce the issue. When you get the blank screen, are there any errors in your DevTools console?

**Comment by Fluzzroz** [comment]
Yes. Error in console: 

> netsuite.js:1 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'value')
    at netsuite.js:1:96535

![image](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/33040640/c8af9a6b-a1d9-419e-8ee7-962e0c5128ce)

**Comment by Fluzzroz** [comment]
I used the same file in 2 other instances. It worked as expected.

**Comment by Fluzzroz** [comment]
I tested more instances and different logins. The problem only occurs in 1 specific instance, regardless of login used.

**Comment by burkybang** [comment]
Interesting. I wonder if a NetSuite update breaks it, and the update hasn't rolled out to everyone yet. Your screenshot is tremendously helpful. I can use that.

**Comment by burkybang** [comment]
Fixed in version 28.7.0
