### ISSUE TITLE
SuiteAdvanced injected styles interacting with custom HTML Suitelet

### ISSUE THREAD

**Issue by RandomHarlz** [burkybang/SuiteAdvanced-Feedback#115]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 
The custom styles of SuiteAdvanced are running on a custom HTML Suitelet and preventing a custom font in the HTML from being used.
___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 
Go to this custom Suitelet: https://tstdrv1509306.extforms.netsuite.com/app/site/hosting/scriptlet.nl?script=843&deploy=1&compid=TSTDRV1509306&h=aa6d9a244d16ef0efa68&lb_id=0
Right hand click and inspect the page title
Review the `font-family` and note that inherited styles from SuiteAdvanced are overriding the font family from the HTML

Then disable the SuiteAdvanced extension in your browser
Refresh the page and review the fonts loading correctly without being overwritten
___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: 
I would expect SuiteAdvanced to detect that the page is custom HTML and not utilising the standard NetSuite UI and therefore not inject custom CSS into the page.
___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 
![image](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/9343418/ff4d94b4-b956-417a-bcd1-f0a312a30d7d)

___

**Additional context**
_Add any other context about the problem here._

Answer:
Hi Adam! 👋

**Comment by burkybang** [comment]
Hey Harley! Thanks for reporting this issue.

**Comment by burkybang** [comment]
I've fixed it. It'll be in the next release.

**Comment by burkybang** [comment]
@RandomHarlz This fix is released now!
