### ISSUE TITLE
Dark Mode Global Search Bar Not Legible

### ISSUE THREAD

**Issue by ToddLofton** [burkybang/SuiteAdvanced-Feedback#119]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: All text entered in the global search bar is black font on black background (dark mode)

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: type any characters into the global search bar while in dark mode

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: the font to be white while in dark mode so it is legible

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 
![image](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/159948655/1f6e7383-af92-4e6b-9e96-6aa3db73b1f5)
![image](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/159948655/bc77120c-cdbe-4e2e-a121-26de049a1177)

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
![image](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/927886/35d7bf78-d9a1-4b2f-a7e0-bc044d4e0cae)

I've resolved the issue and released a new update. It should be available to update to later today.

**Comment by burkybang** [comment]
The update is out now. You can either wait for your browser to poll for updates automatically or do it yourself: [How to Update Chrome Extensions](https://www.youtube.com/watch?v=H1NBPr1mmt4)

**Comment by ToddLofton** [comment]
Works like a charm!  Thanks for the quick response!

Todd Lofton, ERP Administrator IT Support Analyst

Phone: 318-703-4128
Email: ***@***.******@***.***>

From: Adam Smith ***@***.***>
Sent: Tuesday, February 13, 2024 1:20 PM
To: burkybang/SuiteAdvanced-Feedback ***@***.***>
Cc: Todd Lofton ***@***.***>; Author ***@***.***>
Subject: [External]Re: [burkybang/SuiteAdvanced-Feedback] Dark Mode Global Search Bar Not Legible (Issue #119)


The update is out now. You can either wait for your browser to poll for updates automatically or do it yourself: How to Update Chrome Extensions<https://www.youtube.com/watch?v=H1NBPr1mmt4>
