### ISSUE TITLE
Item Fulfillment Form Hiding Fields with SuiteAdvanced Enabled

### ISSUE THREAD

**Issue by st-eez** [burkybang/SuiteAdvanced-Feedback#124]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: When looking at an Item Fullfilment form with custom fields, after loading the page fully, my custom fields dissapear from the page.

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 
1- Go to Item Fulfillment
2- Add custom fields to IF
3- Enter data and Save IF
4- When page reloads, fields will dissapear.
5- If i disable SuiteAdvanced on Page, it will reshow the custom fields.

Also reproducable on all existing IF's.

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: Custom fields should always appear on form

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 

Expected result: 
![image](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/108044540/1ff0a574-f603-4e91-9472-a660a856e7e5)

Current result (With suiteadvanced enabled): 
![image](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/108044540/7455c12e-118f-4716-aba4-0757576bad0b)

___

**Additional context**
_Add any other context about the problem here._

Answer:
Let me know if you need any additional INFO,

Thank you for your great work with SuiteAdvanced!

Steez

**Comment by burkybang** [comment]
Hi Steez! Is the field group collapsed? Try clicking on the field group name.

**Comment by st-eez** [comment]
Wow….

I think i need some sleep 🤣🤣

You were right

Thank you for the awesome help ,

Much appreciated
