### ISSUE TITLE
NetSuite Center Tab disappears

### ISSUE THREAD

**Issue by martjag12** [burkybang/SuiteAdvanced-Feedback#125]
I am using many different NetSuite accounts and with some of the accounts, NetSuite Center Tab just disappears, it is not visible (see screenshot below). With some accounts it is working perfectly. It does not matter if I use Administrator or Custom Role, I still do not see the tab at the top. Only solution currently is to disable SuiteAdvanced completely.

![CleanShot 2024-03-04 at 11 21 51@2x](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/43170825/cf76df48-55ca-487f-8492-7e1119dd6067)

Answer: 

___

**Expected behavior**
I should be able to refresh or type something in the console to get this working for other accounts. Resetting settings from SuiteAdvanced does not help.

Answer: 

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
You are the third person to report this within the last month. The reason for the issue is still unknown, but reinstalling SuiteAdvanced fixes it.
