### ISSUE TITLE
Quick field search on saved search results/criteria

### ISSUE THREAD

**Issue by toyloe** [burkybang/SuiteAdvanced-Feedback#126]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 
When in a saved search I use to be able to quick search a field instead of scrolling through the drop-down.  Others using SA can still use with feature, but I've lost it.  I've checked my settings and have cleared cache in my browser and still cannot get it to work as before.
___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 
Go to any saved search and adding columns or standard criteria
___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: 
To have the quick type option
___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 
![image](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/162230654/46b29d51-5f88-4422-8b18-773722b99af2)
___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
Does this happen if you disable SuiteAdvanced?

**Comment by burkybang** [comment]
I think I know the issue you’re talking about, and I don't think it's related to SuiteAdvanced.

**Comment by toyloe** [comment]
Hi Adam,
Sorry about that, I was thinking it was a SuiteAdvanced feature – I loved the option.  I disabled SA and I still get the same results where you have to hunt through the drop-down.  A colleague of mine has SA and the feature works for him.  I’ll check on his setup and see where the differences are.   Thanks!

Tara Oyloe
Sr ERP Consultant, Enterprise Solutions

***@***.******@***.***>
***@***.***>Direct: 319.296.7709
www.creativeplanning.com<https://www.creativeplanning.com/>
5454 W 110th Street, Overland Park, KS 66211

[A black background with blue text  Description automatically generated with low confidence]

BerganKDV is proud to be part of Creative Planning.  Please update my contact information to reflect my new Creative Planning email.

**Comment by toyloe** [comment]
HI Adam,
I found it!  Our threat locker removed it, but it is a chrome extension called “NetSuite Field Finder”, it’s a fabulous tool 😊  Thanks for your quick response!!

Tara Oyloe
Sr ERP Consultant, Enterprise Solutions

***@***.******@***.***>
***@***.***>Direct: 319.296.7709
www.creativeplanning.com<https://www.creativeplanning.com/>
5454 W 110th Street, Overland Park, KS 66211

[A black background with blue text  Description automatically generated with low confidence]

BerganKDV is proud to be part of Creative Planning.  Please update my contact information to reflect my new Creative Planning email.

From: Tara Oyloe
Sent: Tuesday, March 5, 2024 8:29 AM
To: burkybang/SuiteAdvanced-Feedback ***@***.***>; burkybang/SuiteAdvanced-Feedback ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [burkybang/SuiteAdvanced-Feedback] Quick field search on saved search results/criteria (Issue #126)

Hi Adam,
Sorry about that, I was thinking it was a SuiteAdvanced feature – I loved the option.  I disabled SA and I still get the same results where you have to hunt through the drop-down.  A colleague of mine has SA and the feature works for him.  I’ll check on his setup and see where the differences are.   Thanks!

Tara Oyloe
Sr ERP Consultant, Enterprise Solutions

***@***.******@***.***>
***@***.***>Direct: 319.296.7709
www.creativeplanning.com<https://www.creativeplanning.com/>
5454 W 110th Street, Overland Park, KS 66211

[A black background with blue text  Description automatically generated with low confidence]

BerganKDV is proud to be part of Creative Planning.  Please update my contact information to reflect my new Creative Planning email.

**Comment by burkybang** [comment]
Oh gotcha!

**Comment by toyloe** [comment]
[like]  Tara Oyloe reacted to your message:
________________________________
