### ISSUE TITLE
Expand/Collapse

### ISSUE THREAD

**Issue by Byron1962** [burkybang/SuiteAdvanced-Feedback#13]
When you need to expand or collapse  the field sections I think they should all expand as it dose with native NetSuite. The way you have it working takes 2 clicks to get the job done. 
![Expand-Collapse](https://user-images.githubusercontent.com/99739304/154076656-517b5e1e-3f6a-4bb9-a2d1-8b1fb77e9a4d.png)
Please let me know if you have any questions.

Thank you,

**Comment by burkybang** [comment]
Thanks for the feedback! I've added an option in settings called "Collapse All in Unrolled View" to allow optionally enabling this feature instead of it always being enabled. It'll be disabled by default.

It'll be available in v24.0.0~b5.
