### ISSUE TITLE
Unable to create an "Other Record Field"

### ISSUE THREAD

**Issue by srbalthazor** [burkybang/SuiteAdvanced-Feedback#130]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: When attempting to create a new Other Record Field, the user is redirected to a new Custom Record Field page instead.

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 
1. Navigate to 'Customization > Lists, Records, & Fields > Other Record Fields > New'
2. Notice you are brought to the incorrect page.

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: The user is expected to land on '/app/common/custom/othercustfield.nl' but instead they land on '/app/common/custom/custreccustfield.nl'

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: N/A

___

**Additional context**
_Add any other context about the problem here._

Answer: Disabling SuiteAdvanced on the account immediately fixes the problem

**Comment by burkybang** [comment]
Thank you! I found the issue and fixed it in the next version.
