### ISSUE TITLE
Dark mode - 1 line transaction / communication not readable on white background

### ISSUE THREAD

**Issue by bodawui** [burkybang/SuiteAdvanced-Feedback#131]
**Describe the bug**
When I have 1 line transaction or a case with 1 email sent.
the background is white with gray text, once mouse is over the line it became black with white text.

in case that we have 2 and more lines all is displayed properly.

Answer: 

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. Create a case record
2. describe message
3. save it
4. the message has white background.

Answer: 

___

**Expected behavior**
black background with white text to make it readable

Answer: 

___

**Screenshots**
![image](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/99030435/114c8af4-0f4d-4fc0-8aa6-777612b8d725)

Answer: 

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
I can't seem to reproduce this issue. Maybe some other extension or NetSuite script is interfering.

**Comment by Jacohun1** [comment]
Im running into this issue on quote records for the messages tab sublist and in the quick view for items in the quote. I have windows dark theme enabled and I believe I am also running the "Just Black" chrome theme.

**Comment by burkybang** [comment]
@Jacohun1 Can you try disabling any other dark mode extensions you have to ensure they are not interfering with SuiteAdvanced dark mode?

**Comment by bodawui** [comment]
I do not have any other theme in Chrome, just usual dark mode in Mac OS.

even if any other extension is disabled the issue still persist, and I cannot just switch to light mode any longer :-D it burns my eyes :-D

**Comment by burkybang** [comment]
@bodawui I found the issue. It'll be fixed in the next release.
