### ISSUE TITLE
Dark Mode | Quick Create

### ISSUE THREAD

**Issue by Jacohun1** [burkybang/SuiteAdvanced-Feedback#134]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 
Shortcut is black on a dark background
___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 
Go to any transaction record in dark mode
___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: 
Should be gray? 
___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 
![image](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/6316084/4a7ebc23-d2eb-49e6-a4b3-4e8ab2702900)

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
Thanks. This will be fixed in the next release.
