### ISSUE TITLE
Dark mode  sublist with 1 row is not dark

### ISSUE THREAD

**Issue by eduardRsult** [burkybang/SuiteAdvanced-Feedback#139]
if there is only one row in a sublist, the back ground is white (with light text and therefore unreadable) on hooover it is dark again.
happens on different sublists.

![Screenshot 2024-04-11 at 09 54 00](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/122311607/d7749776-72a4-46d2-9a1f-51b5a0cd9924)

**Comment by burkybang** [comment]
Resolved! It will be fixed in the next release.

Duplicate of https://github.com/burkybang/SuiteAdvanced-Feedback/issues/131
