### ISSUE TITLE
Get SuiteQL

### ISSUE THREAD

**Issue by hminhduc** [burkybang/SuiteAdvanced-Feedback#152]
On Datatable i put some parameter but on Get SuiteQL all parameter revert to ?
How can convert to SuiteQL and keep all parameters pass in Datatable?

**Comment by burkybang** [comment]
My guess is that you're talking about converting a Dataset into SuiteQL. SuiteAdvanced is using an official NetSuite API to do this. The API doesn't support converting variables. You'll have to do that part manually.
