### ISSUE TITLE
CSV Import Status page: Allow disabling Live View

### ISSUE THREAD

**Issue by csilk** [burkybang/SuiteAdvanced-Feedback#159]
The 'Live View' button triggers a refresh of DOM elements at set intervals; this refresh process results in the following issues:

**Loss of Highlight**: When the DOM is refreshed, any highlighted text is no longer visually marked, forcing users to redo the highlighting action, which can be particularly frustrating during tasks that involve searching or comparing data.

My workaround is to disable live view when I need to search/highlight, but this feature cannot be disabled on the CSV import status page (the button is greyed out as per image below); please allow the button to be unchecked in the UI as per other search results pages.

<img width="394" alt="Screenshot 2024-06-29 at 21 58 05" src="https://github.com/burkybang/SuiteAdvanced-Feedback/assets/1517793/2bb9bd3d-f110-4f06-81de-ee4490e2a62e">

**Comment by csilk** [comment]
I don't expect that the loss of highlight issue is fixable but the ability to disable live view on the CSV import status page is an acceptable work around.

**Comment by burkybang** [comment]
Okay, will do for next release! Thanks for the feedback.

**Comment by burkybang** [comment]
I finished making the change, and it will be available in the next release.
