### ISSUE TITLE
Analytics Portlet

### ISSUE THREAD

**Issue by avargas94** [burkybang/SuiteAdvanced-Feedback#16]
**Describe the bug**
Items in the table, not links, when using Analytics Portlets are difficult to read when in Dark Mode. 

**Expected behavior**
Text that isn't a link should be white in the table

**Screenshots**
![image](https://user-images.githubusercontent.com/35619279/156081896-4ca207f3-4c99-42fd-8aae-82d8c8caa77f.png)

**Comment by burkybang** [comment]
Thank you! It's been very difficult to support dark mode EVERYWHERE. That's why it has the "Beta" label on it in settings. I know there must be some unique places I missed. Your bug report helps me so much. 

Just in case I can't find what's in your screenshot when I'm at my computer later, could you please give me some steps for how to get to that Portlet?

**Comment by avargas94** [comment]
The steps are listed below. I also found another spot as well. 

Personalize Dashboard -> Select Analytics -> Setup
![image](https://user-images.githubusercontent.com/35619279/156084186-e3488fd6-0071-4d4e-9314-521ccb933a56.png)

You will also need to fix the background for the list for different analytic reports shown below
![image](https://user-images.githubusercontent.com/35619279/156084317-b6d6dfc9-bf3c-493a-998a-06150f1fba14.png)

Select Sales (Ordered).. Just click on them to you find this one and the report will show the incorrect line coloring. 
![image](https://user-images.githubusercontent.com/35619279/156084414-f8ed20c4-3e3f-40fe-a7f7-efe0580fdacb.png)

**Comment by burkybang** [comment]
I got this looking nice. It'll be available in, v24.1.1, the next version.

![image](https://user-images.githubusercontent.com/927886/156221169-351d2947-ff1e-48b1-9fe8-4330351db64d.png)

![image](https://user-images.githubusercontent.com/927886/156221281-78c949a8-e0c8-42d8-839b-cb27785f484b.png)

**Comment by burkybang** [comment]
v24.1.1 is out now with this fix. Please let me know if it's working okay for you.

**Comment by burkybang** [comment]
@avargas94 v24.1.1 is out now with this fix. Please let me know if it's working okay for you.
