### ISSUE TITLE
link to media files from script logs is wrong

### ISSUE THREAD

**Issue by eduardRsult** [burkybang/SuiteAdvanced-Feedback#160]
in script logs

file: 1111234 

produces now a hyperlink to
https://12345.app.netsuite.com/app/common/media/mediaitemdata.nl?id=1111234
should be IMHO
https://12345.app.netsuite.com/app/common/media/mediaitem.nl?id=1111234

**Comment by burkybang** [comment]
That link looks like a file record URL, but "item" should result in an item URL.

When I try it, it produces a link like this:
https://12345.app.netsuite.com/app/common/item/item.nl?id=1111234

I must be misunderstanding 🤔

**Comment by eduardRsult** [comment]
Sorry i meant file: 1111234

**Comment by burkybang** [comment]
Ah, yes I see the issue now. What's weird is I'm using a NetSuite API to look up the URL path. NetSuite is returning the invalid URL. I'll just add an override for "file".

Thanks so much for reporting the issue! It'll be fixed in the next release.
