### ISSUE TITLE
"Location" field is not visible on Transaction/Sales Order Record when SuiteAdvanced is enabled.

### ISSUE THREAD

**Issue by MarkBirdRock** [burkybang/SuiteAdvanced-Feedback#163]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer:  The native "Location" field is not appearing on Sales Orders (possibly more transactions) when SuiteAdvanced is enabled.  If it's on, the user can quickly see the Location field, but it disappears.

When disabled, the Location field is visible.  The Location field is set to 'visible' on the form.
___

**How to reproduce**

Answer: 
1.  Go to Sales Order.
2. In Main section, "Location. is not visible.
3. Disable SuiteAdvanced in pull-down menu on the tab.
4. The sales order reloads and "Location" is visible again.
___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: You can see the Location field!

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer:  Attached screenshots with before/after.
![SA Bug Report - Location field on Transactions 01](https://github.com/user-attachments/assets/98910d1e-d4bc-4114-a4d2-e5eaf4f60442)

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
The field group is collapsed. Please click the field group header to expand it.

**Comment by burkybang** [comment]
The next release will have a setting to disable collapsible field groups. It will also make collapsed field groups more obvious.
