### ISSUE TITLE
Email popout not readable in dark mode

### ISSUE THREAD

**Issue by srisoff** [burkybang/SuiteAdvanced-Feedback#167]
**Describe the bug**
_A clear and concise description of what the bug is._
When using dark mode, the create email popout is difficult to read. The background is black and the text does not change. 

Answer: 

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
Go to a customer record or a transaction record
2. _Click on...._
Create email. New email, etc. The 
![image](https://github.com/user-attachments/assets/5f8859a1-59cb-424b-89ff-9300761a7eaa)

3. _Scroll down to...._
Select the message tab. Either select a template or type in the message body.
![image](https://github.com/user-attachments/assets/06c7be2c-983b-4c1d-b9d1-79065c5d2dd0)

4. _See error_
No error. The body is very difficult to read as the text does not change color when the background does.

Answer: 

___

**Expected behavior**
_A clear and concise description of what you expected to happen._
The text should switch to White or the background should stay white.

Answer: 

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._
Shown above

Answer: 

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
A fix for this is coming in the next release

**Comment by burkybang** [comment]
This fix is out now! v30.2.0
You can wait for your browser to automatically poll for updates, or you can poll for updates yourself: [How To Update Chrome Extensions](https://www.youtube.com/watch?v=H1NBPr1mmt4)
