### ISSUE TITLE
Checkbox Overlaying Text Fields in Scripted Records Form

### ISSUE THREAD

**Issue by avargas94** [burkybang/SuiteAdvanced-Feedback#17]
**Describe the bug**
Please correct the placement of the Auto Generate ID to a better location. It is currently sitting on top of the text fields

**To Reproduce**
Steps to reproduce the behavior: Create New Scripted Record for the + in the file cabinet.

**Expected behavior**
Move the text to a single line, and place above or below text fields

**Screenshots**
![image](https://user-images.githubusercontent.com/35619279/156113112-a10b2dd8-c287-464a-a3ea-b0d63a59c4ad.png)

**Comment by burkybang** [comment]
Thanks! This is happening because of the horizontal fields view you’re using. I'll make it compatible.

**Comment by avargas94** [comment]
Thanks!.. So far great work! Love the extention

**Comment by burkybang** [comment]
A fix for this will be available in, v24.1.1, the next version.

![image](https://user-images.githubusercontent.com/927886/156252930-e2af3774-4c10-4893-8c83-59673f2a8691.png)

**Comment by burkybang** [comment]
@avargas94 v24.1.1 is out now with this fix. Please let me know if it's working okay for you.
