### ISSUE TITLE
Global Shortcuts and Extension Icon Missing in Weekly Timesheet page

### ISSUE THREAD

**Issue by Rusty-Vermithrax** [burkybang/SuiteAdvanced-Feedback#170]
**Describe the bug**
When you navigate to the Weekly Timesheet page to enter time, the global shortcuts and the extension icon disappear.

**How to reproduce**
1. Navigate to Transaction > Employees > Weekly Timesheet

**Expected behavior**
Global shortcuts and Extension icons should still be there.

**Screenshots**
![image](https://github.com/user-attachments/assets/f1a1cbef-e035-4e38-a4da-583d7f77c60e)

![image](https://github.com/user-attachments/assets/aef91c6a-3a95-4370-953d-db45e3e1b351)

**Comment by burkybang** [comment]
This page is a "new UI" page. It's built completely differently than normal pages. Unfortunately I'm unable to make all features compatible with new UI pages.
