### ISSUE TITLE
Live View not Functional

### ISSUE THREAD

**Issue by thebaaron42** [burkybang/SuiteAdvanced-Feedback#172]
Hello!

Just a heads up that for the last couple of weeks, live view does not work for me.  Specifically notice it on the CSV Import status page.

**Comment by burkybang** [comment]
A fix is coming!

**Comment by burkybang** [comment]
The next release is out now

**Comment by zebra403** [comment]
This is still not working for me on any record type. I have version v30.1.1 is there an update I should have to correct this issue

**Comment by burkybang** [comment]
I found a second issue. It'll be fixed in the next release. Thanks!

**Comment by zebra403** [comment]
When do you expect the next release to be deployed?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by burkybang** [comment]
ETA this week

**Comment by zebra403** [comment]
Hello Adam,

Any update on this fix?
________________________________

**Comment by burkybang** [comment]
@zebra403 I submitted the update today. Just waiting on Google to approve it.

**Comment by burkybang** [comment]
This fix is out now! v30.2.0
You can wait for your browser to automatically poll for updates, or you can poll for updates yourself: [How To Update Chrome Extensions](https://www.youtube.com/watch?v=H1NBPr1mmt4)

**Comment by zebra403** [comment]
Thanks Adam. It works!
________________________________
