### ISSUE TITLE
Issues Restarting Subscription

### ISSUE THREAD

**Issue by HunterJacobs** [burkybang/SuiteAdvanced-Feedback#177]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: When trying to re-activate my subscription I get the following page.

![image](https://github.com/user-attachments/assets/6516cbf0-637f-47e5-bece-53569934af14)

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 
1. Netsuite Home Page logged in
2. Click on suite advanced chrome addon
3. Make sure you stopped your subscription way prior (like a month ago)
4. Update your payment method 
5. Wont let me pay but says last payment was today :(

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: Be able to pay and renew subscription

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: Above
![image](https://github.com/user-attachments/assets/6516cbf0-637f-47e5-bece-53569934af14)
___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by HunterJacobs** [comment]
Update, had to log out, purchase the subscription then it was fine

**Comment by burkybang** [comment]
Glad you got it figured out!
