### ISSUE TITLE
SuiteQL Format messed up

### ISSUE THREAD

**Issue by HunterJacobs** [burkybang/SuiteAdvanced-Feedback#178]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: See screenshot below - SUITEQL Smooshed together - also submenu text options are grayed out

Cleared netsuite cache, browser cache, logged in & out of netsuite and SuiteAdvanced, changed roles, tried different chrome user. Did not try a new device
___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. Go to SuiteQL
2. See Issue
3. View 2nd Screenshot
4. See submenu font issue

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: no smooshed quiteql, darker font

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 
![image](https://github.com/user-attachments/assets/aba10910-3a54-46b7-8d9d-064b0bfb29b8)
![image](https://github.com/user-attachments/assets/7f720a80-d302-46ee-a5f8-6035b1aef277)

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
Thank you! I have these NetSuite 2024.2 compatibility fixes completed already and will be releasing a new version soon.

**Comment by burkybang** [comment]
The next release is out now
