### ISSUE TITLE
Execute Button on M/R is gone in 2024.2

### ISSUE THREAD

**Issue by loicb24** [burkybang/SuiteAdvanced-Feedback#179]
With the 2024.2 version of NetSuite, the Execute button (which is by far the BEST feature of SuiteAdvanced) is gone :(

![image](https://github.com/user-attachments/assets/357fd524-cf8c-412c-9fe7-24534a4c064f)

**Comment by burkybang** [comment]
Thanks! I have fixed this, and it will be working again in the next release.

**Comment by burkybang** [comment]
The next release is out now
