### ISSUE TITLE
Center Background Colors Not Being Applied

### ISSUE THREAD

**Issue by HeavenlyEntity** [burkybang/SuiteAdvanced-Feedback#182]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: The NetSuite center navigation are missing the colors being applied to them. They are rendering transparent instead.

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 

1. Open NetSuite
2. Log in with your username and password
3. Choose a color for navigation bars & headers
4. _No response to color application_

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer:  Color has applied correctly within extension headers and navigation headers. 

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 

![NexSnap-Sep-03-2024_10-39-37_AM](https://github.com/user-attachments/assets/961be853-14a4-40ea-b238-f3718744b037)
![NexSnap-Sep-03-2024_10-44-04_AM](https://github.com/user-attachments/assets/488325c5-079d-4a27-b810-efead0d046a4)

___

**Additional context**
_Add any other context about the problem here._

Answer: I have cleared my cache and reset the settings, and it is still doing the same thing.

**Comment by burkybang** [comment]
This information should help you.

https://suiteadvanced.com/version-30_1_0/#Updated-Minimum-Requirements

https://github.com/burkybang/SuiteAdvanced-Feedback/discussions/180

**Comment by HeavenlyEntity** [comment]
Would be great to downgrade then for specific browsers that are not driven directly by chromium's version i.e. Chrome itself. For integrator browsers like Sidekick, Brave, and Thorium will all have issues with this. Thanks for the reply.
