### ISSUE TITLE
Cannot "Copy" SE results since update

### ISSUE THREAD

**Issue by jfutrell1stphorm** [burkybang/SuiteAdvanced-Feedback#183]
**Describe the bug**
Since the latest NS update, I do not have the "copy" functionality. I have cleared cache. 
<img width="256" alt="image" src="https://github.com/user-attachments/assets/551a9abf-5674-4388-809c-209480f8bbff">

Answer: 

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: 

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
Thank you. This will be fixed in the next release.

**Comment by burkybang** [comment]
This fix is out now! v30.2.0
You can wait for your browser to automatically poll for updates, or you can poll for updates yourself: [How To Update Chrome Extensions](https://www.youtube.com/watch?v=H1NBPr1mmt4)
