### ISSUE TITLE
File Cabinet Issue

### ISSUE THREAD

**Issue by BillGriffin55** [burkybang/SuiteAdvanced-Feedback#184]
**Describe the bug**
When I open the file cabinet, I get a page unresponsive message 
![image](https://github.com/user-attachments/assets/73fa8dd5-2418-4d41-81af-d7e5e8d86698)

Answer: 

___

**How to reproduce**
_go to Documents _> FIles->File cabinet

Answer: 

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: Should open FIle Cabinet

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by BillGriffin55** [comment]
Let me try to disable the NS addins I have to narrow down which one it is. A couple I no longer need since your product has the same functionality.

**Comment by BillGriffin55** [comment]
Adam,

Could it be the number of folders I have in the FC? I have 2 instances one has 14 and it works fine. The one that is failing has 2269 folders

Bill

**Comment by burkybang** [comment]
Yes, I suppose that could affect it. I'll see if I can reproduce that issue. Can you send a screenshot of the page that is causing the issue? You can disable SuiteAdvanced first. Please show the full page and blur any private information. This should give me all the details I need to reproduce the issue, so that I can work on fixing it.

**Comment by BillGriffin55** [comment]
Adam,

Here are screen shots with SuiteAdvanced enabled and disabled also, If I click on a subset of the file cabinet (images) It just takes a very long time to display the 858 images but is does not give the unresponsive error.

Bill

***@***.***

***@***.***

**Comment by burkybang** [comment]
The attachments did not come through. You may need to manually upload them to the GitHub issue: #184

**Comment by BillGriffin55** [comment]
![Pic2](https://github.com/user-attachments/assets/8750fe99-d5b6-407e-8918-020faf5fdf58)

**Comment by BillGriffin55** [comment]
![pic1](https://github.com/user-attachments/assets/59a0f945-50a2-4966-b285-c4158b1f49e2)

**Comment by burkybang** [comment]
Is an automation creating those folders in your File Cabinet root? I would consider organizing those into subfolders. Even without SuiteAdvanced, that looks like a pain to work with. Normally you want as few folders as possible in your root.

**Comment by BillGriffin55** [comment]
I inherited this mess. We are actually moving to a new instance, so the problem doesn’t (and wont) exist there.

Thanks
Bill

**Comment by burkybang** [comment]
Oh fantastic. So happy for you 😃
