### ISSUE TITLE
Menu List is barely readable in Dark Mode

### ISSUE THREAD

**Issue by ghost** [burkybang/SuiteAdvanced-Feedback#187]
While in Dark Mode, all menus are white background with light gray font.  I believe this is due to my NetSuite version being updated to 2024.2 yesterday.

![image](https://github.com/user-attachments/assets/246862e4-e9ba-4d2c-871c-08d1c533a465)

**Comment by burkybang** [comment]
Thank you. This will be fixed in the next release.

**Comment by burkybang** [comment]
This fix is out now! v30.2.0
You can wait for your browser to automatically poll for updates, or you can poll for updates yourself: [How To Update Chrome Extensions](https://www.youtube.com/watch?v=H1NBPr1mmt4)

**Comment by Dominus-Est-Via-Veritas-Et-Vita** [comment]
Looks awesome!

Todd Lofton, ERP Administrator IT Support Analyst

Phone: 318-703-4128
Email: ***@***.******@***.***>

From: Adam Smith ***@***.***>
Sent: Wednesday, September 25, 2024 1:08 PM
To: burkybang/SuiteAdvanced-Feedback ***@***.***>
Cc: Todd Lofton ***@***.***>; Author ***@***.***>
Subject: [External]Re: [burkybang/SuiteAdvanced-Feedback] Menu List is barely readable in Dark Mode (Issue #187)


This fix is out now! v30.2.0
You can wait for your browser to automatically poll for updates, or you can poll for updates yourself: How To Update Chrome Extensions<https://www.youtube.com/watch?v=H1NBPr1mmt4>
