### ISSUE TITLE
Live View does not refresh on Saved Searches

### ISSUE THREAD

**Issue by TechZack** [burkybang/SuiteAdvanced-Feedback#190]
**Describe the bug**
Live View does not work on Saved Searches, it looks like it does do it with the Animation rendering on the page but the Saved Search does not refresh unless you click the Refresh Button

It seems the issue started just before the 2024.2 Issue from what we were discussing in Discord, but I only have noticed this issue recently since the 2024.2 Compatibility Update
___

**How to reproduce**
_Describe steps to reproduce the behaviour. Example:_
1. _Go to any Saved Search on any record type_
2. _Run the Saved Search_
3. _Toggle Live View_

___

**Expected behaviour**
Saved Search to refresh when Live View is toggled.

___

**Comment by burkybang** [comment]
I fixed this issue yesterday on my side. The fix will be in the next release.
