### ISSUE TITLE
Formatting Issue since NetSuite update

### ISSUE THREAD

**Issue by theodditie** [burkybang/SuiteAdvanced-Feedback#193]
**Describe the bug**
I'm not sure if I'm the only one, but since NetSuite recently performed an update on our account, I've been having some formatting issues with SuiteAdvanced. This goes from the menu dropdowns while in dark mode having the text and background both a light color, to the bottom floating bar having extra space under it now.

Answer: 

___

**How to reproduce**
These issues are showing on any page in NetSuite. The menus are only while in Dark Mode, the floating bar would be on any page like editing an item or order.

Answer: 

___

**Expected behavior**
Switching to dark mode should add some more contrast to the menus. The floating bar was a single row before without extra space.

Answer: 

___

**Screenshots**
![dark-mode-menu](https://github.com/user-attachments/assets/a207d659-9961-4679-b6c3-4f719b4de7be)
![floating-bar](https://github.com/user-attachments/assets/d71c4173-4f53-46cb-8487-c19e9c390b86)

Answer: 

___

**Additional context**
For the Dark Mode issue, I wouldn't rule out I did something dumb to my colors on my computer and the timing just worked out with the NS update.

Answer:

**Comment by burkybang** [comment]
A fix is coming very soon
