### ISSUE TITLE
Saved Search filters off-screen

### ISSUE THREAD

**Issue by rar-sth** [burkybang/SuiteAdvanced-Feedback#196]
**Describe the bug**
The filter section is off screen and no way to scroll.

**How to reproduce**
1. Load a saved search in Netsuite that has several filter fields

**Screenshots**
[
![Screenshot 2024-10-03 093735](https://github.com/user-attachments/assets/f0de3db1-b8b8-48f1-aa27-4e582014065a)
](url)

**Comment by burkybang** [comment]
This'll be fixed in the next release. Thanks for reporting it!
