### ISSUE TITLE
about generated SuiteQL 

### ISSUE THREAD

**Issue by hminhduc** [burkybang/SuiteAdvanced-Feedback#198]
After copy generated from tool, it not directly for using. by adding space on each SQL keyword. For example
var suiteQLQuery = `
                SELECT 
                 itemVendor.purchaseprice  
                FROM 
                 item,itemVendor 
                WHERE 
                  item."ID" = itemVendor.item(+)
                  AND ((item."ID" = ? AND itemVendor.vendor IN (?)))    
                `;
To run it no error, i have to add space after SELECT and FORM, WHERE manual.

So how can add this space on generated SuiteSQL?

**Comment by burkybang** [comment]
From where are you copying this? Please provide screenshots.

**Comment by hminhduc** [comment]
This is copy of that SQL . before From, Where dont have a space so that error in runtime.

<img width="1034" alt="image" src="https://github.com/user-attachments/assets/c5da0b35-0444-4e4b-a7a2-a2f938b99c9f">

**Comment by burkybang** [comment]
I don't understand. I see a line break and 2 spaces after SELECT.

**Comment by hminhduc** [comment]
OK, thank you!
So copy that original command is error, then after add space before From and Where keyword (not after) it is run again.

**Comment by burkybang** [comment]
I'm so sorry. I don't understand.

Maybe you could create a screen recording of the issue?

**Comment by hminhduc** [comment]
I'm sorry, today i get run again and all is ok.

**Comment by hminhduc** [comment]
so please close this issue
