### ISSUE TITLE
Dark Mode - Workflows

### ISSUE THREAD

**Issue by avargas94** [burkybang/SuiteAdvanced-Feedback#20]
**Describe the bug**
Can you please correct the coloring on the Workflow States shown in the below image, looks like only one of the states have white text when all of them should have white text. Thanks!

**Screenshots**
![image](https://user-images.githubusercontent.com/35619279/157916039-06e7da9d-cdff-427e-a57c-e0026861b367.png)

**Comment by burkybang** [comment]
Thank you for reporting this! It will be fixed in the next update.

![image](https://user-images.githubusercontent.com/927886/158857581-22943424-3853-4132-bbda-b12c3b97b44f.png)

**Comment by burkybang** [comment]
@avargas94 You should now have the update with this bug fix. Let me know if it's working alright for you.
