### ISSUE TITLE
Redwood Experience is causing plugin to crash frontend

### ISSUE THREAD

**Issue by djokicpn** [burkybang/SuiteAdvanced-Feedback#216]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 
Its just crashing whole UI, enable Redwood Experience and you will see what I'm talking about. Dashboard have infinite loop loaders etc.
___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: 

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._
<img width="1327" alt="image" src="https://github.com/user-attachments/assets/87345bcb-0083-4fcd-b9b1-2b8c3f2f7e20" />

Answer: 

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
Thanks! I've fixed this for the next release.
