### ISSUE TITLE
Save Drop down menu Appearing in wrong spot

### ISSUE THREAD

**Issue by ShotyMcFat** [burkybang/SuiteAdvanced-Feedback#217]
**Describe the bug**

Answer: When Selecting Alternative Options to Save a Transaction, the Drop down Menu Shows up at the Top of the Screen (see Image Below)

___

**How to reproduce**

Answer: 
1. Edit Any Transaction
2. Using the Save Button at the Bottom of the Screen, Hover over the Drop down Arrow
3. The Menu Shows up at the top of the Screen

___

**Expected behavior**

Answer: Menu should be Immediately Above the Save and Arrow button

___

**Screenshots**

Answer: ![Save Drop down](https://github.com/user-attachments/assets/94991756-562d-4222-8ba0-e97387b2a969)

**Comment by burkybang** [comment]
Thanks. This'll be fixed in the next version.
