### ISSUE TITLE
Field ID's on column line fields

### ISSUE THREAD

**Issue by jkig77** [burkybang/SuiteAdvanced-Feedback#22]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Similar to your advanced feature to show field ID's on body fields, would be nice to have on line fields as well.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by burkybang** [comment]
@jkig77 It should already be showing the field IDs for line fields. Where are you looking that it's not doing that?

**Comment by jkig77** [comment]
I'm on a PO & SO record > Lines section and Item Master > Location.lines
section.

**Comment by burkybang** [comment]
Here? I have it only showing in edit mode because the field IDs are not available in the HTML of the page in view mode.

![image](https://user-images.githubusercontent.com/927886/160457694-3f6a4873-67c2-48ec-ad2d-50b425fc14b9.png)

**Comment by jkig77** [comment]
Got it. I see it now in edit mode. Understood.

By the way, is there a running list of features you have developed into
this product?

**Comment by burkybang** [comment]
Great! I'm still working on an official list, but you can view my work in progress here:
https://docs.google.com/document/d/1Li0rMI7tcQGUfF2kF9ub6FHD3IeVt1cfEYjbEBZT850/edit?usp=sharing
