### ISSUE TITLE
Email Monthly Receipts

### ISSUE THREAD

**Issue by cdi-amarp** [burkybang/SuiteAdvanced-Feedback#24]
Hello,

My boss has approved this subscription/monthly charge for me, but requires receipts for tax/accounting purposes.
Are you able to email me a "receipt" for every monthly charge? I can then forward to accounting.
I already switched the subscription to his credit card.

Thanks,

**Comment by burkybang** [comment]
Hi @cdi-amarp. Yes, I can help with that. I'm unable to know who you are based on your username. Can you shoot me an email at support@burkybang.com?
