### ISSUE TITLE
Show Field ID's in menu is missing?

### ISSUE THREAD

**Issue by jkig77** [burkybang/SuiteAdvanced-Feedback#25]
Show Field ID's in menu is missing?

**Comment by jkig77** [comment]
Sorry I thought it was a global setting to turn on/off, I must have not
been on a particular record. Now I see it when I'm on a record, but
disappears like when I'm on a dashboard view. Understood how this works
now. TY

**Comment by burkybang** [comment]
Awesome. No worries at all
