### ISSUE TITLE
Bulk add permissions not showing properly in dark mode

### ISSUE THREAD

**Issue by srisoff** [burkybang/SuiteAdvanced-Feedback#26]
**Describe the bug**

When using dark mode and using the bulk Add/edit/remove feature, the action list does not show clearly. In my instance, it was not able to be seen at all due to contrast on my screen.

**To Reproduce**
1. Go to *URL*

Not an error but a display issue. Pic below.

**Expected behavior**

**Screenshots**

![2022-05-06 SuiteAdvanced Bug](https://user-images.githubusercontent.com/33101549/167159389-8e522f60-73c3-4274-80f4-e99b628c0207.jpg)

**Additional context**

**Comment by burkybang** [comment]
Hi @srisoff. Thanks for reporting that issue! I have actually already fixed this one. I just haven't released it yet. It should be out soon.

![image](https://user-images.githubusercontent.com/927886/167166909-c722fbcf-fdfc-42c3-8c6d-764130b70b64.png)

**Comment by burkybang** [comment]
I just submitted v24.3.0 to Google for review. They've been approving them within ~24 hours lately, so you should have the update soon.
