### ISSUE TITLE
Auto refresh all portlets on load of dashboard

### ISSUE THREAD

**Issue by srisoff** [burkybang/SuiteAdvanced-Feedback#27]
**Is your feature request related to a problem? Please describe.**
Live view is nice but has to be turned on every time dashboard is visited. 

**Describe the solution you'd like**
There is already an extension that auto refreshed all portlets upon load of the dashboard. It would be nice to have this included in your extension to limit the number of extensions required to download.

**Describe alternatives you've considered**
Using the portlet refresher extension already. Works but would be cool if it was a feature of yours as well.

**Additional context**
This happens completely in the background. No way to screenshot it.

**Comment by burkybang** [comment]
So you’re just looking to have a way for Live View on the dashboard to be on automatically?

**Comment by burkybang** [comment]
> Would it be possible to have a setting to auto start live view? Maybe in the live view section?

Yes, I can add that. I think it might be beneficial to just have the state of Live View on Dashboards remembered, so that if you enable it and then refresh the whole page, it remains enabled.

> a portlet refresh every time the dashboard loads

Actually, this is already a feature of SuiteAdvanced. All Portlets automatically refresh when a Dashboard initially loads.

**Comment by srisoff** [comment]
That would work. I think it would basically be the same as the settings then because those go by role anyways.

Best regards,

Scott Risoff
Senior ERP Consultant

***@***.***
Direct:  319.739.2941
Fax:  319.294.9003
www.bergankdv.com<http://www.bergankdv.com/>
www.linkedin.com/in/scott-risoff<http://www.linkedin.com/in/scott-risoff>

CONNECT WITH US
[linkedin]<https://www.linkedin.com/company/bergankdv>  [twitter] <https://twitter.com/BerganKDV>   [facebook] <https://www.facebook.com/BerganKDV>   [instagram] <https://instagram.com/bergankdv/>   [youtube] <https://www.youtube.com/channel/UCuA7FKd4TNJ4XqXhikC39Fg>

[O-NetSuite-Cert-SuiteFoundation-horz-rgb]
[MCTS_2013(rgb)_1309]

________________________________
***Caution: this email came from an external source. Please think before clicking on any links or attachments.***

**Comment by burkybang** [comment]
This feature will be in the next version. Thanks!
