### ISSUE TITLE
Link to the Script Execution Log from a script or script deployment record.

### ISSUE THREAD

**Issue by Sandersland** [burkybang/SuiteAdvanced-Feedback#30]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when..._

Answer: No existing problem with the extension. It's a nuisance going to the script record looking to view logs only to realize that the error occurred yesterday and is being excluded from the current view. 

___

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

Answer: I would like a link or button that would open a new window to the Script Execution Log page with the desired script selected in the filters.

___

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Answer: I simply script this or write a tampermonkey(extension) script myself but thought this would be a good feature for you to add. :)

___

**Additional context**
_Add any other context or screenshots about the feature request here._

Answer:
![image](https://user-images.githubusercontent.com/17189382/170702453-460468b3-fe8f-4018-a911-28274041c210.png)

**Comment by burkybang** [comment]
That's a great idea! It'll be in the next update.

![image](https://user-images.githubusercontent.com/927886/170734436-cfddf442-c254-40e1-b245-ccf04509053c.png)

**Comment by burkybang** [comment]
@Sandersland This new feature is available now!
