### ISSUE TITLE
Field Changed not firing on Multi-Select fields with the extension enabled

### ISSUE THREAD

**Issue by Rumancikz** [burkybang/SuiteAdvanced-Feedback#32]
**Describe the bug**
Answer:  field changed event in client-side scripts isn't firing when the extension is enabled.

___

**How to reproduce**
Answer: 
1. Go to a multi-select field that has a client script on it.
2. Console log the field changed event and open the brower's console.
3. Select an option and observe no log being generated.
4. Disable the extension on the same page
5. Select an option and observe there is now a log
___

**Expected behavior**

Answer: 
Select an option and observe a log showing the field changed event has fired.
___

**Screenshots**

Answer: 
Extension Enabled:
![image](https://user-images.githubusercontent.com/68083947/174108694-cd410556-7a5a-49c1-95b1-f2b8d410faea.png)
Extension Disabled:
![image](https://user-images.githubusercontent.com/68083947/174109600-be3eb730-2df6-4f28-81b5-1d51c70efaee.png)

**Comment by burkybang** [comment]
Thank you for submitting this bug! I'll have it fixed in the next update.
