### ISSUE TITLE
Resize columns on editable sublists

### ISSUE THREAD

**Issue by makomninos** [burkybang/SuiteAdvanced-Feedback#33]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when..._

Answer: We have some REALLY long Item names and you expand them out on all forms (e.g. sales order, work order, ...). Love that it freezes the first column BUT it doesn't give me the option to resize it.

___

**Describe the solution you'd like**
_A clear and concise description of what you want to happen._

Answer: I'd like the ability to either decide to wrap the first column OR even better if I could resize it. Thank you!

___

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._

Answer: 

___

**Additional context**
_Add any other context or screenshots about the feature request here._

Answer: LOVE YOUR PRODUCT!! Just installed yesterday.

**Comment by makomninos** [comment]
If you can’t resize, is there a way to keep the top row freeze but choose to wrap the first column? Or keep the top row freeze and not do any freeze on the column?

**Comment by burkybang** [comment]
I figured out a solution for this. Resizable columns will be in the next release. Thanks for the idea!

**Comment by makomninos** [comment]
Wonderful news!!

Thank you. 

Margie

**Comment by burkybang** [comment]
I just submitted the next release with this new feature (version 24.5.0) to Google. It should be out in the next day or two.

**Comment by burkybang** [comment]
The update is out now. Let me know what you think of the new feature!

**Comment by makomninos** [comment]
Hi Adam – this is great!! Looks like you made them all resizable.

 

Thank you so much for being so responsive and so quick about the enhancement. We will be talking about your product at our upcoming user group meeting. I will miss the meeting, but added my 2 cents for Cory to mention. It won’t be until the end in the Open Forum section when users can ask questions and add comments. 

 

Thanks again!

 

Margie Komninos
