### ISSUE TITLE
Cannot add new message in a Case

### ISSUE THREAD

**Issue by Tumbao33** [burkybang/SuiteAdvanced-Feedback#34]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 
When editing a Case record, you cannot add a new Message. The Message box does not show up. The title for the Message box is there, but not the box. 
___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 

1. Go to an existing Case.
2. Edit the record
3. Check the New Message box.
4. Try to add a text in the Message box

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: 
Able to add a new message
___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 
![image](https://user-images.githubusercontent.com/109157186/178508847-3a31efc6-3da0-481f-9870-98599d09fd1e.png)

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
Thanks for reporting this bug! I have fixed it, and I will be pushing a new release (v24.5.1) soon.

**Comment by burkybang** [comment]
I submitted the update to Google. They usually approve my updates within a day.

**Comment by Tumbao33** [comment]
Hi Adam,

I can confirm that it is working now.


Thanks!

Cory
