### ISSUE TITLE
Sublist Field ID not showing on sublist

### ISSUE THREAD

**Issue by RezaSeedin** [burkybang/SuiteAdvanced-Feedback#37]
**Describe the bug**
Sublist Field ID not showing

**How to reproduce**
_Describe steps to reproduce the behaviour. Example:_
1. _Go to Inventory Adjustment/ Sales order
2. Pless Control + I
3. Sublist values not being shown

**Screenshots**
![image](https://user-images.githubusercontent.com/18523110/180140484-a6589dd4-7785-40ce-af06-698de3cbe9ec.png)

**Comment by burkybang** [comment]
Thanks Reza! This one was actually just fixed yesterday, and the update is out now.

Duplicate issue: https://github.com/burkybang/SuiteAdvanced-Feedback/issues/35

**Comment by burkybang** [comment]
The update to fix this is out now.
