### ISSUE TITLE
Saved Search Split View sorting

### ISSUE THREAD

**Issue by Tumbao33** [burkybang/SuiteAdvanced-Feedback#41]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: When in a saved search split view, clicking on the headers in the preview results does not sort by the column header clicked. Nothing happens. 

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: I would expect to be able to change the sort when clicking on a column header in the split view preview.

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
Thanks! I'll check it out.

**Comment by burkybang** [comment]
I found the issue. It'll be fixed in the next release (v24.5.3).

**Comment by burkybang** [comment]
The update to fix this is out now.
