### ISSUE TITLE
Color theme selected for Release Preview account apply to production account as well

### ISSUE THREAD

**Issue by Tumbao33** [burkybang/SuiteAdvanced-Feedback#45]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: The color theme chosen in the Release Preview account also applies to production. 

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 
1. Log in to Release Preview
2. Change the color theme
3. Go back to Production account
4. Color theme chosen in RP applies to Prod
___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: I would expect the color theme to only apply to RP like the sandbox settings do.

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by burkybang** [comment]
Hey Cory. This is actually intended behavior. When you open SuiteAdvanced settings while in an RP account, notice how the Role dropdown still has the name of the equivalent production account. RP themes use their equivalent production account themes.

I used to allow RP accounts to have their own themes too, but the internal session ID for an RP account set by NetSuite changes. The session ID is the unique ID for a role across all accounts, so I use this as the unique key to set themes per role. When the session ID changes, it adds the new one to the Roles dropdown, and it will start causing the Roles dropdown to become cluttered with many duplicate RP accounts. Eventually Chrome's sync storage will fill up, and it will prevent SuiteAdvanced settings from being saved until you manually remove the RP accounts from the Roles dropdown. The best solution I could come up with was to disallow setting unique themes for RP accounts.

The session ID for a sandbox account gets changed as well after a sandbox refresh, but I figured that happens was less often than RP account session ID changes, so it's not as big of a problem. If you do see duplicate sandbox roles in the Roles dropdown, you can use the Remove Role button to remove each one. Duplicates will have a number at the end such as "(2)" or "(3)" while the original will have no number. The one with the highest number is the latest one, so you should remove the ones with lower numbers including the original. I don't auto remove them in case two accounts actually have the same name.

I hope this makes sense. Let me know if you have any questions or suggestions.
