### ISSUE TITLE
Item sublist field IDs misaligned on Item Fulfillments and Item Receipts

### ISSUE THREAD

**Issue by RezaSeedin** [burkybang/SuiteAdvanced-Feedback#51]
**Describe the bug**
IR lines : item labels misaligned

Answer:  IR lines : a few columns are not aligned with the internal ids

___

**Screenshots**
![image](https://user-images.githubusercontent.com/18523110/189780491-7f6bbae7-805a-4765-8e2d-f11a76049efc.png)

**Comment by hminhduc** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/6736560/192227557-7568c933-b6a0-4bf8-80e8-a885f5fe5795.png">
same problem on my IR screen

**Comment by burkybang** [comment]
I have yet again found a more reliable way to show field IDs on sublists. It'll be available in the next release. Thanks for reporting this!
