### ISSUE TITLE
Dark Mode - Customer Dashboard > Customer (default) Portlet

### ISSUE THREAD

**Issue by skeeeon** [burkybang/SuiteAdvanced-Feedback#52]
**Describe the bug**

When Dark Mode is enabled, not all text within the Customer (Default) portlet is changed to the inverse color. This leads to unreadable text unless highlighted.
___

**How to reproduce**

1. Enable Dark Mode
2. Navigate to a Customer
3. View the Customer Dashboard
4. If not already present, add the Customer (Default) Portlet to the dashboard

___

**Expected behavior**

All text within the portlet should be white and visible without the need for highlighting.

___

**Screenshots**
![image](https://user-images.githubusercontent.com/9888807/190037499-5432f1c6-355d-4d30-9d9f-4bdc992336f1.png)
![image](https://user-images.githubusercontent.com/9888807/190037588-ea006460-14af-43a9-a106-5fc732e34e66.png)

**Comment by burkybang** [comment]
Thank you for the bug report and all the details! This really helps me.

**Comment by burkybang** [comment]
I found the issue and resolved it. You will see the change in the next update!
