### ISSUE TITLE
show id field of subrecord

### ISSUE THREAD

**Issue by hminhduc** [burkybang/SuiteAdvanced-Feedback#54]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6736560/190972385-8176462d-7d23-4785-9b70-3cb548228087.png">

How can you upgrade to show when open subrecord on a form, as picture above..

Thank you!

**Comment by burkybang** [comment]
Actually, this already works. You just need to press Ctrl or Cmd + I again once you open the inventory detail since it's technically a different page.

![image](https://user-images.githubusercontent.com/927886/198400332-98a5fc41-610c-4c1c-825f-2525f6f1f9c3.png)
