### ISSUE TITLE
Menus sometime appear in reverse

### ISSUE THREAD

**Issue by amarchetanpatel** [burkybang/SuiteAdvanced-Feedback#65]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 
Menus sometime display in reverse order
___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 
Happens randomly when clicking in menu bar
___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: Normally displays 'Account' first.

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 
![Screen Shot 2022-11-09 at 1 52 43 PM](https://user-images.githubusercontent.com/109744151/200922188-1bfd19a3-694e-4566-b42a-4e57a9836c1d.png)

**Comment by burkybang** [comment]
That's definitely strange. I have doubts that SuiteAdvanced is doing that. See if you can reproduce it with SuiteAdvanced disabled.

**Comment by burkybang** [comment]
Closed because I believe this is unrelated to SuiteAdvanced
