### ISSUE TITLE
When long JSON is present page  does not load. (350k in JSON payload)

### ISSUE THREAD

**Issue by RezaSeedin** [burkybang/SuiteAdvanced-Feedback#66]
**Describe the bug**
I have a log JSON field (long text) and If the script has populated it, non of the subtabs load. Tested on Item

Item record
Field on the Custom subtab
JSON field length 350000

Disabling the plugin shows all the subtabs correctly

![image](https://user-images.githubusercontent.com/18523110/204163279-beda9715-9541-47d5-a2e9-636599544be3.png)
![image](https://user-images.githubusercontent.com/18523110/204163308-0a7034b5-eb25-4cb1-9793-fc40ad0cc470.png)

**Comment by RezaSeedin** [comment]
Console log

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
    at netsuite.js:1:34450
    at NodeList.forEach (<anonymous>)
    at netsuite.js:1:33930

![image](https://user-images.githubusercontent.com/18523110/204167430-9eb82d7f-5cf5-4c61-bbd2-7ed168dd0c74.png)

**Comment by burkybang** [comment]
Resolved
