### ISSUE TITLE
Moving Between NetSuite Accounts

### ISSUE THREAD

**Issue by andruwaltringer** [burkybang/SuiteAdvanced-Feedback#69]
### Discussed in https://github.com/burkybang/SuiteAdvanced-Feedback/discussions/68

<div type='discussions-op-text'>

<sup>Originally posted by **andruwaltringer** January 23, 2023</sup>
I was just wondering if I am doing something wrong when moving to and from NetSuite accounts. I am having to log back in every time I do this and this is listed as one of the features for this extension. Thanks in advance!</div>

**Comment by burkybang** [comment]
Is this still an issue?
