### ISSUE TITLE
Checkbox style dissappearing

### ISSUE THREAD

**Issue by InitiativeWorking** [burkybang/SuiteAdvanced-Feedback#72]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 
After a re-login into NetSuite, all checkboxes seem to be just a dot sitewide. No matter the location, the checkboxes appear as a dot. The hitbox is the size of the dot too, it's not just a visual bug.
![image](https://user-images.githubusercontent.com/87781169/214883339-a3f1e3bc-9c05-4053-ad49-8638ba085462.png)

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 
1. Leave the site unattended without logging off.
2. Login after some time away. For example, the next workday.
3. See error
___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: 
Checkboxes appear as checkboxes
___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 
![image](https://user-images.githubusercontent.com/87781169/214883933-c7059df6-78e1-4fde-823c-0d6aa6e331f2.png)
![image](https://user-images.githubusercontent.com/87781169/214884382-d1eef7c2-3e0c-487c-86f0-17a1dd20bef8.png)

___

**Additional context**
_Add any other context about the problem here._

Answer:
Usually, for a quick fix, I deactivate SuiteAdvanced on tab, refresh, and re-activate and the checkboxes show up with their normal style after I have refreshed the pages with the error.
![image](https://user-images.githubusercontent.com/87781169/214883377-80b5e119-3349-4f1e-8df2-2398777c3269.png)

Maybe a compatibility problem with https://darkreader.org/ ? This is my only idea so I'm not too sure what's up.
___

Keep the good work up!! 👏 The app is amazing!

**Comment by burkybang** [comment]
You've found an extremely old NetSuite bug! This happens with and without SuiteAdvanced. To fix it, just do a hard reload to clear your cache.

This website I just found seems to explain how to do it pretty well:

https://help.codehs.com/en/articles/4951972-how-to-clear-your-browser-cache-and-hard-refresh#h_dfff8ab987

**Comment by InitiativeWorking** [comment]
I see! Thank you very very much for the quick answer!

Have a great day!
