### ISSUE TITLE
NS 2023.1: Switching roles to current page

### ISSUE THREAD

**Issue by mounirelchoueiri** [burkybang/SuiteAdvanced-Feedback#75]
After the NS 2023.1 release, a feature that I'm missing is switching roles in the current page. I use that one multiple times daily!

**Comment by burkybang** [comment]
@mounirelchoueiri I recreated the ability to switch to the current page for an _account_ in NS 2023.1. Switching to the current page in a _role_ will be coming soon.

(Please let me know if you have any better icon ideas. I'm not too fond of the pop-out icon for this, but I wanted to get the feature out quickly.)

![image](https://user-images.githubusercontent.com/927886/221755782-c98d9d9d-253d-4fc5-b9d0-a2645afa0fb7.png)

**Comment by burkybang** [comment]
I just submitted another update. This one has support for switching roles to the current page again.

![image](https://user-images.githubusercontent.com/927886/221981212-d620ef53-140a-4ab3-8b47-3ea2e45c43f6.png)
