### ISSUE TITLE
Time Entry Message Title Color White on Dark Mode

### ISSUE THREAD

**Issue by HeavenlyEntity** [burkybang/SuiteAdvanced-Feedback#79]
**Time Entry Color Title White when in dark mode**

This is a pretty simple fix bug but the title for the message box when Time has been submitted successfully is white instead of dark so it can be read.

**How to reproduce**
1. _Go to *Enter weekly time sheet*_
2. _Add a few time entries to equal up to 40hrs._
3. _See the message title in white at the top upon successful submission_

**Expected behavior**
Should be a dark title to be able to read the title in the box.

**Screenshots**
![image](https://user-images.githubusercontent.com/39228141/229652011-b17e5872-2154-4576-8d47-cf8a10333bfa.png)

**Additional context**
Might want to test the rest of the other dialog types to ensure the rest of the message boxes are the correct color.

**Comment by burkybang** [comment]
Thank you! I'm working on an update to fix a lot of other dark mode issues that occur due to NetSuite updates. I'll make sure to get this fixed as well.

**Comment by HeavenlyEntity** [comment]
Absolutely! Let me know how I can help! 🏆

**Comment by InitiativeWorking** [comment]
This is also affecting the script view on dark mode
![image](https://user-images.githubusercontent.com/87781169/234097104-772bda72-1f32-402f-8742-62eb73db539f.png)

hope it helps

**Comment by burkybang** [comment]
I have fixed the script editor in version 26.7.2

I will get to the time entry message title color soon

**Comment by burkybang** [comment]
I have fixed the time entry message title color in version 26.7.3 along with lots of other dark mode and theming improvements.
