### ISSUE TITLE
sublist dont show field id

### ISSUE THREAD

**Issue by hminhduc** [burkybang/SuiteAdvanced-Feedback#81]
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/6736560/233758864-9d8bfb62-dc2f-42dd-aefc-d5d282e30db4.png">

Im on a custom record, and sublist's field id still hidden when edit mode and Ctrl-I for show Field Id.
Im on newest SA version

**Comment by burkybang** [comment]
It doesn't always work everywhere. It depends on the way the particular NetSuite page is set up in the background. Some pages don't have the field IDs for sublists embeded.
