### ISSUE TITLE
File Cabinet Move Button Bug

### ISSUE THREAD

**Issue by Rumancikz** [burkybang/SuiteAdvanced-Feedback#9]
**Describe the bug**
The file cabinet's move button seems to improperly place results in the drop-down based on its name. For example, the folder named "SCS Cloud" contents are put after "SCS Cloud (Unapplied)" even though the move still aims at the correct folder if it is targeted towards a child of "SCS Cloud".

**To Reproduce**
1. Go to Filing Cabinet
2. Have identically named folders with one having something following it EX: (Unapplied)
3. Attempt to move something using the move button
4. Open the dropdown
5. There will now be entries that should be under the shorter named one that end up under the longer named one

**Expected behavior**
The child entries should follow the parent folder

**Screenshots**
![image](https://user-images.githubusercontent.com/68083947/145248675-07d87746-332f-4cf1-a641-641cf8403b94.png)

**Additional context**

**Comment by burkybang** [comment]
This is due to a NetSuite bug with sorting those options, and I don't have a way to fix their bug efficiently, so I'm remove this feature altogether in the next release. I may add it back if I determine a way to fix their bug efficiently or if they miraculously fix it.
