### ISSUE TITLE
In script executions logs some json gets beautified some does not.

### ISSUE THREAD

**Issue by eduardRsult** [burkybang/SuiteAdvanced-Feedback#91]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 
In script executions logs some json gets beautified some does not.
Previously only JOSN that was inclomplete (cutoff by log details character limit) was not beautified. Now it just parses some and some not.
___

**How to reproduce**
_Describe steps to reproduce the behavior. 
Run a map reduce that creates many logs with json. Some longer some shorter.

___

**Expected behavior**
_A clear and concise description of what you expected to happen._
All json beautified
___

**Screenshots**
I have 2 (arbitrary) situations 
1. only system logs
2. all logs

I made screenshots for each of them in 3 conditions
1. with this plugin (SA)  (black theme)  While the other plugin is turned off (full refresh of page)
2. with the other plugin that conflicts with SuiteAdvanced with SA turned off (full refresh of page)
3. vanilla with both plugins turned off. (full refresh of page)

___

**Additional context**
I am pretty sure this worked better before.
Nice that the scriptIds are clickable to the record type. 
Would be great to have an easy way to link to an instance like discussed on Linkedin

![Screenshot 2023-05-31 at 11 48 17](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/122311607/96222f4b-1566-41de-a013-049ce4e6405c)
![Screenshot 2023-05-31 at 11 56 03](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/122311607/8bf69da5-e6cb-4549-84ea-1fd147f5bc59)
![Screenshot 2023-05-31 at 11 55 46](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/122311607/07206cd0-5250-4da8-a232-c32b85928fe4)
![Screenshot 2023-05-31 at 11 49 08](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/122311607/934fa48c-1c08-446b-ad0a-5c0d709fb703)
![Screenshot 2023-05-31 at 11 48 56](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/122311607/83cdfdf6-856a-4d9c-865f-e174fb1dab8b)
![Screenshot 2023-05-31 at 11 48 32](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/122311607/c99e5ac9-d509-4282-9417-e4c893c889bb)

**Comment by burkybang** [comment]
Are you using `.stringify(value, null, 2)` before logging the objects to the log? If so, that could be the issue.

**Comment by burkybang** [comment]
@eduardRsult Are you using `.stringify(value, null, 2)` before logging the objects to the log? If so, that could be the issue.

**Comment by eduardRsult** [comment]
Yes sometimes the module I use spits that out. Or it is added instead of the default  toString() method to error objects since they are sometimes not only thrown but also saved.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

Met vriendelijke groet,
​Kind regards,
Eduard Gradenwitz
+31 (0)85 – 303 78 44
www.rsult.one
Lübeckweg 2, 9723 HE, Groningen
Confidentiality Notice | This e-mail message, including any attachments, is for the sole use of the 
​intended recipient(s) ​and may contain confidential or proprietary information. Any unauthorized 
​review, use, disclosure or distribution is prohibited. If you are not the intended recipient, 
​immediately contact the sender by reply e-mail and destroy all copies of the original message.
________________________________

**Comment by eduardRsult** [comment]
Is there a way you could handle this like the other plugin? It's valid JSON after all.

**Comment by burkybang** [comment]
Yeah, I'll see what I can do

**Comment by burkybang** [comment]
I found a solution. It'll be in the next release (ETA a few days).

**Comment by burkybang** [comment]
I submitted a new release to the Chrome Web Store. It'll be available whenever Google approves it.

**Comment by burkybang** [comment]
Update: It's been approved.
