### ISSUE TITLE
drag-drop from VS won't upload and give false positive

### ISSUE THREAD

**Issue by Fluzzroz** [burkybang/SuiteAdvanced-Feedback#94]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 
The drag & drop feature in which a user can drag a file from Visual Studio's explorer into NetSuite's File Cabinet in order to upload or update a file will lead to the pop up of 2 alerts. One says the file is being uploaded, but will stay at 0% forever, and the other says that the file has been successfully uploaded (but it's not true).
___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 
Open NetSuite's File Cabinet
Open Visual Studio
Drag a file from VS's explorer into NS's file cabinet.
Validate that 2 pop ups appear and the file is not uploaded.

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: 
The file in NS is updated to match the one in VS.
___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 
![drag-drop from VS wont upload and give false positive](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/33040640/533fe011-0e79-4f26-88fa-043c025ae068)

___

**Additional context**
_Add any other context about the problem here._

Answer:
Perhaps this feature is only applicable to the WebStorm IDE, in which case this is not a bug report but a feature request.

**Comment by Fluzzroz** [comment]
I kept referring to my IDE as Visual Studio, but to be specific, I'm using the free Visual Studio Code.
And to be even more specific, here's it's _about_ section:

Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by burkybang** [comment]
@Fluzzroz I don't have VS Code installed, and I have not been able to reproduce this issue with WebStorm. Does the issue also happen if you drag and drop from File Explorer?

**Comment by Fluzzroz** [comment]
No.
I can drag/drop from VS Code into the File Explorer and vice-versa (using
Win 11, have not tested other OS).

VS Code is free and easy to install.

**Comment by burkybang** [comment]
I'm wondering if you experience the same issue if you drag a file from Windows File Explorer into the NetSuite file cabinet.

**Comment by burkybang** [comment]
Okay, thank you. I just wanted to narrow down if the problem is indeed an issue with dragging and dropping from _VS Code_ or if it is some issue with dragging and dropping from _your computer_.

I'll give it a try when I get some time.
