### ISSUE TITLE
Sublist filter does nothing on the Create Deposit page

### ISSUE THREAD

**Issue by Sandersland** [burkybang/SuiteAdvanced-Feedback#95]
**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 
Sublist filters are not functional from the create deposit page
___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 

1. Go to [the create deposit page](https://system.netsuite.com/app/accounting/transactions/deposit.nl)
2. Choose any account and wait for results to populate
3. Update the start date on the sublist filter section
4. Observe that nothing happens

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: 
I expect that the sublist results change when the filters are updated
___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 
n/a
___

**Additional context**
_Add any other context about the problem here._

Answer:
It works as expected when the extension is disabled

**Comment by burkybang** [comment]
I'm seeing the same behavior when SuiteAdvanced is disabled. I don't think this is a bug with NetSuite.
