### ISSUE TITLE
Extension not working on NS 2023.2

### ISSUE THREAD

**Issue by KTsarlz** [burkybang/SuiteAdvanced-Feedback#98]
The extension stopped working on one of my accounts running the latest version of NS. 
Is it not yet updated to work yet? Or I'm missing something

I also emailed for feedback a week ago and there was no response

**Comment by burkybang** [comment]
I released an update last week with some NetSuite 2023.2 compatibility updates. If something isn't working, please describe what's not working.

I don't seem to have the email you sent. Sorry about that.

**Comment by burkybang** [comment]
Please provide the following details.
___


**Describe the bug**
_A clear and concise description of what the bug is._

Answer: 

___

**How to reproduce**
_Describe steps to reproduce the behavior. Example:_
1. _Go to *URL*_
2. _Click on...._
3. _Scroll down to...._
4. _See error_

Answer: 

___

**Expected behavior**
_A clear and concise description of what you expected to happen._

Answer: 

___

**Screenshots**
_If applicable, add screenshots to help explain your problem._

Answer: 

___

**Additional context**
_Add any other context about the problem here._

Answer:

**Comment by KTsarlz** [comment]
The settings pane isn't showing up 

![ScreenShot 2023-08-30 at 23 21 30](https://github.com/burkybang/SuiteAdvanced-Feedback/assets/9140507/d3e22f86-472e-4075-8021-3e3bc0c95327)

**Comment by KTsarlz** [comment]
@burkybang Any update or findings?

**Comment by burkybang** [comment]
Hey sorry. A hurricane disrupted my life this week.

I'm not certain what could be causing that issue. I haven't experienced it myself, and you’re the first one to report it.

Try uninstalling and reinstalling SuiteAdvanced. Back up your settings first if you care not to lose them using the Export option at the bottom of the SuiteAdvanced settings page.

If that doesn't work, please send me an email at support@burkybang.com to schedule a meeting, so you can share your screen, and I can investigate.

**Comment by KTsarlz** [comment]
Oh! So sorry to hear that. 

I did the reinstalling prior to raising the issue here, issue persists. I also just tested a while ago and the issue persists. 

I did try to test in another browser, and it seemed to work. My main browser is ungoogled-chromium which the extension stopped working.

**Comment by burkybang** [comment]
Okay, that's an important detail that I'm sure is causing the issue. If you can tell me how to install that browser, I'll see if there's anything I can do to make SuiteAdvanced compatible with it when I get some time.

**Comment by KTsarlz** [comment]
Here - https://github.com/ungoogled-software/ungoogled-chromium

I'm using it on a Mac

**Comment by mkohn82** [comment]
I'm having the same issue on 2023.2, tried uninstalling and reinstalling with no success - nothing is working and the settings pane is absent like the screenshot above.

Using Chrome version 116.0.5845.141 on Windows 11

**Comment by burkybang** [comment]
Okay, please email me to schedule a one on one. I need to investigate on your computer since I can't reproduce the issue.

support@burkybang.com

**Comment by mkohn82** [comment]
Appreciate the quick follow up but no need. Clearing all browser data did the trick.

Thanks!
